version: "3"

services:
  app:
    image: mrtg-test
    container_name: mrtg-test
    ports: 
    - 80:80
    build: 
      dockerfile: ./Dockerfile
      context: .
    volumes:
    - ./app:/usr/app/src